#© 2021 izak Murdock

apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-stedi-izak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prod-stedi-izak
  template:
    metadata:
      labels:
        app: prod-stedi-izak
    spec:
      containers:
        - name: prod-stedi-izak
          image: us-docker.pkg.dev/byui-scrum-team-11am-mst/izak-api/stedi-api:latest # This image needs to refer to the NEW Artifact registry repositorry
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secrets-izak
                  key: REDIS_PASS
            - name: REDIS_HOST
              value: "redis-stedi-izak"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "0"
            - name: KAFKA_BROKER
              value: "localhost:9092"
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: izak-twilio-dev
                  key: twilio_token
          ports:
            - containerPort: 443
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 4567
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: prod-stedi-izak-nodeport
spec:
  selector:
    app: prod-stedi-izak
  type: NodePort
  ports:
    - port: 80
      targetPort: 4567
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prod-stedi-izak-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: prod-stedi-izak-public # This IP has not been created yet - need to create first
    networking.gke.io/managed-certificates: prod-stedi-izak-certificate
    kubernetes.io/ingress.allow-http: "true"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prod-stedi-izak-nodeport # This needs to match line 53
            port:
              number: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: prod-stedi-izak-certificate # This needs to match line 68
spec:
  domains:
    - izak.cit262.com # This is a DNS record that has not been created yet - we need to create that first
    
